import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { IoSettingsSharp } from "react-icons/io5";
import {
  AiFillInstagram,
  AiFillTwitterCircle,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import { useState, useContext } from "react";
import Navbar from "./navbar";
import { ContextProvider } from "@/Context";
import { Context } from "@/Context";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  const { darkMode, setDarkMode } = props;
  return (
    <ContextProvider>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Bharath's CV</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="px-10 bg-slate-200 dark:bg-gray-900 dark:text-slate-50">
          <section className=" min-h-screen">
            <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
            <div className="text-center ">
              <h1 className="text-5xl font-semibold text-teal-600 ">
                BHARATH
              </h1>
              <h3 className="text-3xl py-3 ">Student In SP</h3>
              <p className="text-md text-gray-600 py-5 dark:text-gray-400">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam
              </p>
            </div>
            <div className="text-4xl flex justify-center mt-5 gap-10 text-gray-600">
              <AiFillInstagram />
              <AiFillTwitterCircle />
              <AiFillYoutube />
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
              <Image
                alt="none"
                src={deved}
                fill
                style={{ objectFit: "cover" }}
              />
            </div>
          </section>
          <section className="min-h-screen">
            <div className="flex justify-center">
              <div>
                <h1 className="text-4xl font-semibold text-center py-10">
                  About Me
                </h1>
                <div className="lg:flex gap-10 justify-center ">
                  <div className="text-center shadow-xl p-10 rounded-xl my-10">
                    <Image
                      src={code}
                      width={100}
                      height={100}
                      className="mx-auto"
                      alt="none"
                    />
                    <h1 className="text-3xl font-semibold text-teal-600 py-2">
                      Course
                    </h1>
                    <p className="text-md text-gray-600 py-5 dark:text-gray-400">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam
                    </p>
                    <p className="text-md text-gray-600 py-5 dark:text-gray-400">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam quod, voluptate, quia, voluptates quas
                      voluptatibus quibusdam quae quidem quos quas voluptatibus
                      quibusdam quae quidem quos
                    </p>
                  </div>

                  <div className="text-center shadow-xl p-10 rounded-xl my-10">
                    <Image
                      src={design}
                      width={100}
                      height={100}
                      className="mx-auto"
                    />
                    <h1 className="text-3xl font-semibold text-teal-600 py-2">
                      Design
                    </h1>
                    <p className="text-md text-gray-600 py-5 dark:text-gray-400">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam
                    </p>
                    <p className="text-md text-gray-600 py-5 dark:text-gray-400">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam quod, voluptate, quia, voluptates quas
                      voluptatibus quibusdam quae quidem quos quas voluptatibus
                      quibusdam quae quidem quos
                    </p>
                  </div>
                  <div className="text-center shadow-xl p-10 rounded-xl my-10 ">
                    <Image
                      src={consulting}
                      width={100}
                      height={100}
                      className="mx-auto"
                    />
                    <h1 className="text-3xl font-semibold text-teal-600 py-2">
                      Helping
                    </h1>
                    <p className="text-md text-gray-600 py-5 dark:text-gray-400 ">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam
                    </p>
                    <p className="text-md text-gray-600 py-5 dark:text-gray-400">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam quod, voluptate, quia, voluptates quas
                      voluptatibus quibusdam quae quidem quos quas voluptatibus
                      quibusdam quae quidem quos
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    </ContextProvider>
  );
}
